name: Build and publish Docker image

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency: production

jobs:
  publish:
    name: Build and publish Docker image to GitHub Packages
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Auth GitHub
        id: auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_API_TAGGING: true
          WITH_V: false
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: patch
          DEFAULT_BRANCH: main
          RELEASE_BRANCHES: main

      - name: Create a GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.version.outputs.changelog }}

      - name: Add tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}},value=${{ steps.version.outputs.new_tag }}
          flavor: latest=auto

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: Set up Docker Build
        id: build
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
